### ISSUE TITLE
Project description is missing at the top of the page.

### ISSUE THREAD

**Issue by spshetty** [KaranDagar/FSE-2011-Crystal---old#1]

**Comment by KaranDagar** [comment]
Also, from where READme starts the details about the project starts.

**Comment by KaranDagar** [comment]
As per my understanding, the tool description is at the top. Please provide more details to your query.

Thanks,
Karan

**Comment by KaranDagar** [comment]
Has been closed in the final repo. ( one on Software tool demos)

**Comment by KaranDagar** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2011-Crystal#1
