### ISSUE TITLE
Link ot the original project website is missing at the top of the page.

### ISSUE THREAD

**Issue by spshetty** [KaranDagar/FSE-2011-Crystal---old#2]

**Comment by KaranDagar** [comment]
I forked it from the original. It may not be at the top, but its definitely above the middle.

**Comment by KaranDagar** [comment]
As per my understanding, the tool description is at the top. Please provide more details to your query.

Thanks,
Karan

**Comment by KaranDagar** [comment]
Has been closed in the final repo. ( one on Software tool demos)

**Comment by KaranDagar** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2011-Crystal#2
