### ISSUE TITLE
Repo not properly forked

### ISSUE THREAD

**Issue by jentsan** [KaranDagar/FSE-2011-Crystal---old#6]
This repo does not seem to be properly forked as it has the history of the original repo and it does not say "forked from..." under the repo name.

**Comment by KaranDagar** [comment]
Hi,
I am not sure if it was specified anywhere that we have to write" forked from" . Also the example repo does not specify that. And in disclaimer, I have stated it quite clearly. 
Thanks,
Karan

**Comment by jentsan** [comment]
Hi,
No, you don't write that. When it is properly forked it will be there automatically. And the example repo doesn't say that because it isn't a forked repo. You can view lecture 8 at the time 1:10 to see that he shows it.
Thanks,
Jen

**Comment by KaranDagar** [comment]
Has been closed in the final repo. ( one on Software tool demos)

**Comment by KaranDagar** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2011-Crystal#6
